---
repos:
  - repo: local
    hooks:
      - id: merge-files
        name: merge-files
        entry: .merge.sh
        language: script
        types: [shell]
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        files: README.md
